### ISSUE TITLE
Couldn't connect remote mqtt server

### ISSUE THREAD

**Issue by Isuru40** [soft2tec/universal_mqtt_client#19]
its getting error like this 

`I/flutter ( 5762): Connection Status: UniversalMqttClientStatus.connecting
I/flutter ( 5762): Connection Status: UniversalMqttClientStatus.disconnected
I/flutter ( 5762): Connection Status: UniversalMqttClientStatus.disconnected
E/flutter ( 5762): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: UniversalMqttClientConnectException: Unknown connection error.`

i put initialize line as

`final client = UniversalMqttClient(broker: Uri.parse('ws://34.x.x.x:1883'));`   x indicate remote server ip

could you please guide me

**Comment by lucacasonato** [comment]
You seem to be using the wrong port to connect to a WebSocket MQTT broker. The default port for MQTT over WebSocket is `9000`. Port `1883` is only used for MQTT over TCP. If you want to use TCP you should use a connection string like this: `tcp://34.x.x.x:1883`.

Can you make sure that the MQTT server is running and available at this IP address? You can check this using a tool like MqttFx on your computer. This error usually comes up when the device can not find a valid route to the server (because of a firewall or if the server is not responding).

**Comment by lucacasonato** [comment]
Closing because stale. Feel free to reopen the issue if this persists.
